const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let polls=0,posts=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://ews.test/**',route=>{const req=route.request(),url=new URL(req.url());let body={ok:true};if(!url.pathname.startsWith('/api/'))return route.fulfill({contentType:'text/html',body:fs.readFileSync('operations.html','utf8')});
if(url.pathname.endsWith('/machines')){polls++;body.nodes=[{node_id:'n1',hostname:'Рабочая машина',status:'online',agent_version:'0.3.16',last_seen_at:new Date().toISOString()}];body.commands=[{node_id:'n1',command_type:'update',status:'accepted'}]}
else if(req.method()==='POST'){posts.push(req.postDataJSON());return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'no_available_nodes'})})}
else if(url.pathname.endsWith('/projects'))body.projects=[];else body.logs=[];
return route.fulfill({contentType:'application/json',body:JSON.stringify(body)})});
await page.goto('https://ews.test/');await page.locator('#token').fill('test-token');await page.locator('#login button').click();await page.locator('#nodes h2').waitFor();assert.equal(await page.locator('nav a').count(),2);assert.equal(await page.locator('#nodes .spin').count(),1);
await page.locator('#prompt').fill('Проверить данные');await page.locator('#submitTask').click();await page.getByText('Задание не запущено: Нет доступных нод на связи.').waitFor();assert.equal(posts.length,1);assert.equal(posts[0].task_text,'Проверить данные');assert.equal(await page.locator('#prompt').inputValue(),'Проверить данные');
await page.getByRole('button',{name:'SSH',exact:true}).click();await page.locator('#sshDialog[open]').waitFor();await page.locator('#closeSsh').click();
await page.clock.install();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});const before=polls;await page.clock.fastForward(180000);assert.equal(polls,before);
await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForFunction(()=>document.getElementById('notice').textContent.startsWith('Состояние получено'));assert.ok(polls>before);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/ews-operations-mobile.png',fullPage:true});await page.locator('#logout').click();const atLogout=polls;await page.clock.fastForward(120000);assert.equal(polls,atLogout);assert.deepEqual(errors,[]);await browser.close();console.log('Operations browser: navigation, error handling, animation, mobile layout, hidden polling and logout PASS');})().catch(e=>{console.error(e);process.exit(1)});
